version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mono2micro-backend
    container_name: backend
    hostname: 'localhost'
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases

  functionality_refactor:
    build:
      context: ./tools/functionality_refactor/src
    image: functionality_refactor
    container_name: functionality_refactor
    command: /app/web_service
    hostname: 'localhost'
    ports:
      - 5001:5001
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases

  frontend:
    build:
      context: ./frontend/
    image: mono2micro-frontend                                                     
    container_name: frontend
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 3000:3000
    stdin_open: true
    restart: unless-stopped
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true